name: Minimal meson build in Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
    - name: install minimal requirements
      run: |
          sudo apt-get update && \
          sudo apt-get install -y libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libunwind-dev googletest \
          gstreamer1.0-plugins-good
    - name: add ppa:nnstreamer/ppa
      run: sudo add-apt-repository ppa:nnstreamer/ppa && sudo apt install -y ssat
    - run: echo "TMPDIR=$(mktemp -p $(pwd) -d)" >> $GITHUB_ENV
    - run: echo "TMPDIR=$TMPDIR"
    - run: echo "TMPDIR using ENV.TMPDIR=${{ env.TMPDIR }}"
    - uses: BSFishy/meson-build@v1.0.3
      continue-on-error: true
      with:
        action: test
        options: -v
    - run: find ${{ env.TMPDIR }} -exec ls -al {} \;



# TODO: add more subplugins to be built
# TODO: add unit testing
# TODO: add valgrind testing
